name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Cache Vendor
        id: cache
        uses: actions/cache@v3
        with:
          path: ./vendor
          key: vendor-${{ runner.os }}-${{ github.ref }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |  # 上から順に優先的に復元する
            vendor-${{ runner.os }}-${{ github.ref }}-
            vendor-${{ runner.os }}-${{ github.base_ref }}-
            vendor-${{ runner.os }}-

      - name: Composer Install
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Setup Laravel
        run: |
          cp .env.example .env
          php artisan key:generate
          touch database/database.sqlite

      - name: Run Lint
        run: composer lint

      - name: Run Analyze
        run: composer stan

      - name: Run Test
        run: composer test
